version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_HOST=postgres
      - DB_NAME=secrets_db
    depends_on:
      - redis
      - postgres
    volumes:
      - /vault/secrets:/vault/secrets:ro
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=secrets_db
      - POSTGRES_USER_FILE=/vault/secrets/db-creds
      - POSTGRES_PASSWORD_FILE=/vault/secrets/db-creds
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - /vault/secrets:/vault/secrets:ro
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

volumes:
  redis-data:
  postgres-data:

networks:
  app-network:
    driver: bridge 